spring:
  config:
    activate:
      on-profile: local

---
server:
  port: 8081
spring:
  application:
    name: account-service
  datasource:
    url: jdbc:postgresql://localhost:5433/mybankdb
    username: devadmin
    password: devadmin123pass
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.yaml

---
server:
  port: 8080
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:postgresql://postgres:5432/mybankdb
    username: devadmin
    password: devadmin123pass